# Generated by Django 4.1.7 on 2023-03-21 21:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='format: required, max characters: 150', max_length=150, verbose_name='entry title')),
                ('description', models.CharField(help_text='Enter a brief description of what you bought.', max_length=255, verbose_name='entry description')),
                ('memo', models.CharField(help_text='Not required, memo of the purchase.', max_length=255, null=True, verbose_name='memo')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Required, max digits 10.', max_digits=10, verbose_name='total price')),
                ('tax_year', models.IntegerField(default=2023, help_text='required, automatically added', verbose_name='tax year')),
                ('purchase_date', models.DateField(default=datetime.date.today, help_text='required, automatically added', verbose_name='purchase date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_img', models.ImageField(blank=True, null=True, upload_to='entry_images')),
                ('categroy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.paymentmethod'),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxes.status'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
